package ElectionList;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import VotingList.VotingList;

import javax.swing.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author HP-Pavillion
 */
public class ElectionList extends javax.swing.JFrame {

    /**
     * Creates new form ElectionList
     */
    Statement s;
    String[] strings;
    String username;
    public ElectionList(Statement s,String username) {
        this.username=username;
        System.out.println("username="+this.username);
        this.s=s;

        String sql = "select ELECTION_NAME,DATE from new_election";
        ResultSet result= null;
        try {
            result = s.executeQuery(sql);
            ArrayList<String>arrayList=new ArrayList<>();
            while(result.next()){
//                 strings = new String[]{"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};
                arrayList.add(result.getString(1)+" <"+result.getString(2)+">");
            }
            strings=new String[arrayList.size()];
            int j=0;
            for(int i=arrayList.size()-1;i>-1;i--)
            {
                strings[j]=arrayList.get(i);
                j++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }


        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        elist = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        elist.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 51, 0), null, null));
        elist.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        elist.setForeground(new java.awt.Color(102, 102, 0));
        elist.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        elist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(elist);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Election List");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(98, 98, 98)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(257, 257, 257)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void elistMouseClicked(java.awt.event.MouseEvent evt) {

        // TODO add your handling code here:
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            System.out.println("index="+index);
            String str[]=strings[index].split("<");
            str[1]=str[1].substring(0, str[1].length() - 1);
            try {

                Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(str[1]);
                Date date2=new Date();

                if(date1.getYear()==date2.getYear()&&date1.getMonth()==date2.getMonth()&&date1.getDate()==date2.getDate())
                {
                    String tablename= str[0].substring(0,str[0].length()-1)+str[1];
                    tablename=tablename.replace('-','_');
                    String sql="select * from "+tablename+"voting where username='"+username+"'";
                    ResultSet r=s.executeQuery(sql);
                    if(!r.next())
                    {
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                String tablename= str[0].substring(0,str[0].length()-1)+str[1];
                                tablename=tablename.replace('-','_');
                                new VotingList(s,tablename,username).setVisible(true);
                            }
                        });
                    }else {
                        JOptionPane.showMessageDialog(this, "You already voted for this!");
                    }

                }
                else{
                    JOptionPane.showMessageDialog(this, "Election is not on Today!");

                }
            } catch (ParseException e) {
                e.printStackTrace();
            } catch (SQLException e) {
                e.printStackTrace();
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElectionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElectionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElectionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElectionList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ElectionList(s).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify
    private javax.swing.JList elist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}

