/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Admin.Admin;
import ElectionList.ElectionList;
import AdminElectionList.AdminElectionList;
import ForgotPswd.ForgotPswd;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;

/**
 *
 * @author USER
 */
public class LogIn extends javax.swing.JFrame {
    /**
     * Creates new form LogIn
     */
    Connection  connect;
    Statement s;

    public LogIn() {
        initComponents();
        String url="jdbc:mysql://localhost:3306/VOTING";
        String user="root";
        String pass="root";

        try{
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection(url, user, pass);
            s = connect.createStatement();

        }
        catch(Exception ee)
        {
            JOptionPane.showMessageDialog(null,ee.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordtf = new javax.swing.JTextField();
        loginbt = new javax.swing.JButton();
        signupbt = new javax.swing.JButton();
        forgotpswdlb = new javax.swing.JLabel();
        adminlogbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("College E-Voting System");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Username");

        usernametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametfActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        passwordtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtfActionPerformed(evt);
            }
        });

        loginbt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginbt.setText("Login");
        loginbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    loginbtActionPerformed(evt);
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });

        signupbt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signupbt.setText("Sign up");
        signupbt.setAlignmentY(0.0F);
        signupbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtActionPerformed(evt);
            }
        });

        forgotpswdlb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        forgotpswdlb.setForeground(new java.awt.Color(0, 0, 255));
        forgotpswdlb.setText("Forgot Password?");
        forgotpswdlb.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new ForgotPswd().setVisible(true);
                    }
                });
            }
        });
        adminlogbt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminlogbt.setText("Admin Login");

        adminlogbt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                adminlogbtActionPerformed(e);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(210, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(loginbt)
                                                .addGap(54, 54, 54))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(268, 268, 268)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(usernametf)
                                                .addComponent(passwordtf, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                                        .addComponent(forgotpswdlb)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(signupbt)
                                                .addGap(78, 78, 78)
                                                .addComponent(adminlogbt)))
                                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(usernametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(forgotpswdlb)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(loginbt)
                                        .addComponent(signupbt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminlogbt))
                                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void usernametfActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void loginbtActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException, SQLException {

        // TODO add your handling code here:
        System.out.println("usernametf="+usernametf.getText()+" passwordtf="+passwordtf.getText());
        try{

        String sql = "select * from stud_signup where AADHAR="+usernametf.getText()+" and PASSWORD='"+passwordtf.getText().trim()+"'";
        ResultSet r= s.executeQuery(sql);
        if(r.next())
        {

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new ElectionList(s,usernametf.getText().trim()).setVisible(true);

                }});
        }else {
            sql = "select * from PROF_SIGNUP where AADHAR=" + usernametf.getText() + " and PASSWORD='" + passwordtf.getText().trim() + "'";
            r = s.executeQuery(sql);
            if (r.next()) {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new AdminElectionList(s).setVisible(true);

                        usernametf.setText("");
                        passwordtf.setText("");
                    }
                });
            } else {
                System.out.println("Login Error");
                JOptionPane.showMessageDialog(this, "Please Enter Correct username and password!");
            }
        }
        }catch(SQLSyntaxErrorException e){
            JOptionPane.showMessageDialog(this, "Please Enter Correct username and password!");
        }

    }

    private void passwordtfActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void signupbtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }
    private  void adminlogbtActionPerformed(java.awt.event.ActionEvent evt)
    {
        System.out.println("usernametf="+usernametf.getText()+" ,passwordtf="+passwordtf.getText());
        if(usernametf.getText().equals("admin")&&passwordtf.getText().equals("123")) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Admin(s).setVisible(true);
                }
            });
            usernametf.setText("");
            passwordtf.setText("");

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton adminlogbt;
    private javax.swing.JLabel forgotpswdlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginbt;
    private javax.swing.JTextField passwordtf;
    private javax.swing.JButton signupbt;
    private javax.swing.JTextField usernametf;
    // End of variables declaration                   
}
