package Candidate;

import ElectData.ElectData;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.sql.Statement;

public class Candidate extends javax.swing.JFrame {
    ElectData electionData;
    Statement s;
    int count;
    String[] candidateName;
    /**
     * Creates new form Candidate
     */
    public Candidate(Statement s,ElectData electData) {
        this.s=s;
        this.electionData=electData;
        this.count=0;
        this.candidateName=new String[electionData.Candidate_Count];

        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cndNameField = new javax.swing.JTextField();
        addBt = new javax.swing.JButton();
        submitBt = new javax.swing.JButton();
        countlb = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Candidate Name");

        addBt.setText("Add");

        submitBt.setText("Submit");

        countlb.setForeground(new java.awt.Color(0, 0, 204));
        countlb.setText("0 Candidates added");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(cndNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(addBt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(34, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(countlb, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cndNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addBt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(countlb)
                                .addGap(29, 29, 29)
                                .addComponent(submitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        addBt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(count<electionData.Candidate_Count)
                {
                    candidateName[count++]=cndNameField.getText().trim();
                    countlb.setText(count+" Candidates added");
                    cndNameField.setText("");
                }else{
                    JOptionPane.showMessageDialog(null,"Maximum "+electionData.Candidate_Count+" Candidate Allow");
                }

            }
        });

        submitBt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            if(count==electionData.Candidate_Count){
                try {
                    String sql = "INSERT INTO NEW_ELECTION" +
                            "(ELECTION_NAME,CANDIDATE_COUNT,DATE,START_TIME,END_TIME)" +
                            "VALUES('"+ electionData.Election_Name.trim() + "','" + electionData.Candidate_Count + "','" + electionData.date.trim() + "','" + electionData.Start_Time + "','" + electionData.End_Time + "')";

                    boolean b=s.execute(sql);
                    if(b==false) {
//                        sql = "create table " + electionData.Election_Name + "'(candidatename varchar(25),vote int);'";
                            sql="create table "+electionData.Election_Name.trim()+electionData.date.replace("-","_").trim()+ "(candidatename varchar(25),vote int);";
                        int re=s.executeUpdate(sql);
                        if(re==0) {
                            for(int i=0;i<count;i++)
                            {
                                sql="INSERT INTO "+electionData.Election_Name.trim()+electionData.date.replace("-","_").trim()+" values('"+candidateName[i]+"',0)";
                                b=s.execute(sql);

                            }
                            sql="create table "+electionData.Election_Name.trim()+electionData.date.replace("-","_").trim()+ "voting(username varchar(25));";
                             re=s.executeUpdate(sql);

                            JOptionPane.showMessageDialog(null,"New Election Created Successfully");
                            dispose();
                        }
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }else {
                JOptionPane.showMessageDialog(null,"Please add total"+electionData.Candidate_Count+" Candidate!");

            }

        }

        });

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Candidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Candidate(2).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addBt;
    private javax.swing.JTextField cndNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel countlb;
    private javax.swing.JButton submitBt;
    // End of variables declaration                   
}
